#----------------------------------------------------------------------
# This file was generated by C:\Python27\Lib\site-packages\wx-2.8-msw-unicode\wx\tools\img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

wx = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAABMpJ"
    "REFUWIV1V0FO8zwUHD/bSQoqVEJihXoBDsEFuAEb9lyAE7CCM/RQCLFjAxISW5Q2sR37X5Qx"
    "L/34LVVVEsee92bePMecnJwUEYFzDgCQc8Y0TVgsFpimCcYYWGvRdR2stfDew1oLAGiaps4H"
    "gGEYUErBMAyYpgkhBFhrkVKCMQY5Z4gIUkoQERhj4Eop9WVr7f6mc3Vz7z1EBADQti2cc/WX"
    "c4b3HjlnpJTQtm0FZIyBiFQQOWeUUurmAFBKgeOFtRYigpwzYozoug5t2wIAuq6D9x7eezRN"
    "UzPhvcc0TSilIMYIEcE4jvU9bsbNjTHg4HxnjNkjcQ4ppYp2miaklNB1HUopsNaiaRp47+Gc"
    "w2q1Qs65LmaMAdfifP6LSE19KaVS5r2HyznXlHNz7z0AQETqAt/f3/j6+kLf9xUoN2Vk0zTh"
    "5uYGb29veH9/R865gmLKc84VXM4ZZrlclqZpkFKqIiTv2+0WTdMghADvfX3JOYcYIwDAOVd5"
    "vri4wOvrKwDg8vISMUaM44gYY42eQJgJMcZgmqbKE1VLxZJjPic9nMsoqQs9uJH3fpYpVtH/"
    "ilBXwSxdP9dUOIBaKSklDMNQN6cQqSXvPWKMtWJY+sJU8CGjpsBIjS4lpp+gSIVWeSmlio9g"
    "qammaer7wqjatq0ccTIj1IBKKbUaNEAqmyPnXANiAMweqwYAhBMZDdOjOWZ0dC/SQ/C6Kjjo"
    "mMyAzpa1di9AkX0GiJgRM1UhhFl96xJiVv4Sl17n0E1ZDXzPcaK+GUKo9zQ4Oh91Qqposewn"
    "mm9WAjVBYxvHcV8FjIyo+U9nJAimTeuEgNgXDkVIipxzs01JWUoJ0jRN5YkvHXI2S5mKkpEN"
    "wzDLGLPGatGU5ZxB4xMRSIxxhpatU5sFWymv9Wa6ivQQETRNU0ESPEHQWYWT+YC8sbdzQ91o"
    "2Mk0qO12OytFXVGcJyKVNpao6EVom9pEuq6rCubCLEVdGX8Z0V/X2k1zznsr5kNGR1Dk8bDr"
    "UVRaJyklhBBmNNB0tC60FQPYt2P6su7lLDfe4wIsL7ZvmpJzbuYDIYRKCfvBXwcTYadi7WuE"
    "LEPeZ+r0gUNr4+joqC7MjFDUWkf60CPjOM54ZY1SNNyckeq+wPc4R1PAzfiObuG6GzreIGq6"
    "HBelKPmvI9Y2bq3FYrGoAHa7XeWcgLVpEZDQq3n0ZuQAoMHpzUgPB/nnRjo7WoQarHNufybU"
    "7TGEMDMLbVDjOKLrun8qoW1bjOOIw7Hb7X6PXT/8a0OrTqhNghOI0Dn3Wy4/wABUP08poe/7"
    "WQlzfHx8YLPZYL1eY7vdou977HY7hBAQQqjzzenpadFuRZ5EBDHGuvEh/zxgAL+9P6WE29tb"
    "PDw8zMyL4/n5GXd3d3h5efk9U5yentYOQm71CZj/XdfNapmfZQTCBZmh5XKJq6srbDabf4AA"
    "QN/3uL+/h1mtVgXYf1xwY90DKChtTLTdQ4/gODxl55xxfn6O6+trPD09zYAIa1SnVB8i6WZU"
    "LeccHrFo4RSetm/nHD4/P7HZbHB8fIz1eo3Hx8d9cGdnZ4Wb0HLZ8ymqQ/cjMC3aw88v7Sfs"
    "jDzk6I9TGYZh1qVYIswKF9auV01EUaQ/03WXZLYoZh7JmJn/ANyL7lspkPYwAAAAAElFTkSu"
    "QmCC")
getwxData = wx.GetData
getwxImage = wx.GetImage
getwxBitmap = wx.GetBitmap
getwxIcon = wx.GetIcon

